# Generated by Django 4.1 on 2022-10-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ability1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='ability2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='ability3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='ability4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='lvl',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='order',
            field=models.IntegerField(),
        ),
    ]
