# Generated by Django 4.1 on 2022-11-02 16:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0006_game_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bag',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='ability1',
            new_name='exp',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='ability2',
            new_name='mana',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='ability3',
            new_name='pv',
        ),
        migrations.AlterField(
            model_name='bag',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='bag',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag', to='core_user.game'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='core_user.game'),
        ),
        migrations.AlterField(
            model_name='team',
            name='lvl',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterUniqueTogether(
            name='bag',
            unique_together={('game_id', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('game_id', 'order')},
        ),
        migrations.RemoveField(
            model_name='team',
            name='ability4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pseudo',
        ),
        migrations.CreateModel(
            name='PetStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField()),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('lvl', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pv', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petStore', to='core_user.game')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('game_id', 'order')},
            },
        ),
    ]
