# Generated by Django 4.1 on 2022-11-03 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0007_alter_bag_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
