# Generated by Django 4.1 on 2022-11-04 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0009_alter_bag_amount_alter_bag_model_id_alter_bag_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='petstore',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
