# Generated by Django 4.1 on 2022-11-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0011_alter_team_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bag',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='petstore',
            unique_together=set(),
        ),
    ]
