# Generated by Django 4.1 on 2022-11-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0012_alter_bag_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='position',
            field=models.CharField(default='start', max_length=30),
        ),
    ]
