# Generated by Django 4.1 on 2022-11-29 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0014_alter_bag_order_alter_team_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
