# Generated by Django 4.1 on 2022-12-04 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0015_alter_bag_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gold',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
