# Generated by Django 4.1 on 2022-12-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0016_alter_game_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='pdf')),
            ],
        ),
    ]
